### ISSUE TITLE
[问题]请问下招行的公钥要怎么加载呢 

### ISSUE THREAD

**Issue by zjkyz8** [deatil/go-cryptobin#1]
```
if publicKey == nil {
		if keyData, err := base64.StdEncoding.DecodeString(viper.GetString("keys.publicKey")); err != nil {
			return false, err
		} else {
			if publicKey, err = x509.ReadPublicKeyFromHex(hex.EncodeToString(keyData)); err != nil {
				return false, err
			}
		}
	}
	if signByte, err := base64.StdEncoding.DecodeString(signature); err != nil {
		return false, err
	} else {
		hexString := hex.EncodeToString(signByte)
		r, _ := new(big.Int).SetString(hexString[:64], 16)
		s, _ := new(big.Int).SetString(hexString[64:], 16)
		return sm2.Sm2Verify(publicKey, msg, []byte(viper.GetString("config.uid")), r, s), nil
	}
```
请问这种加载方式和验签方式对吗

**Comment by deatil** [comment]
招行给你们的公钥是哪种？base64编码后的吗？还是pem格式的？

**Comment by deatil** [comment]
如果是跟私钥一样的格式，看起来你的代码是没有问题的

**Comment by zjkyz8** [comment]
看着是base64编码的

**Comment by deatil** [comment]
> 看着是base64编码的，我看您的示例代码里没有关于银行公钥验签相关逻辑呢，目前这个代码只是验签失败，其他加载证书部分似乎都没有问题

示例代码里是用的私钥生成的公钥。

**Comment by deatil** [comment]
> 看着是base64编码的，我看您的示例代码里没有关于银行公钥验签相关逻辑呢，目前这个代码只是验签失败，其他加载证书部分似乎都没有问题

结果是验证结果是false，其他的没有返回error的吧

**Comment by zjkyz8** [comment]
> > 看着是base64编码的，我看您的示例代码里没有关于银行公钥验签相关逻辑呢，目前这个代码只是验签失败，其他加载证书部分似乎都没有问题

对，没有其他错误，只是返回false

**Comment by deatil** [comment]
> > > 看着是base64编码的，我看您的示例代码里没有关于银行公钥验签相关逻辑呢，目前这个代码只是验签失败，其他加载证书部分似乎都没有问题
> 
> 对，没有其他错误，只是返回false

你把r s的错误信息也做个判断看看有没有报错

**Comment by zjkyz8** [comment]
> > > > 看着是base64编码的，我看您的示例代码里没有关于银行公钥验签相关逻辑呢，目前这个代码只是验签失败，其他加载证书部分似乎都没有问题
> > 
> > 
> > 对，没有其他错误，只是返回false
> 
> 你把r s的错误信息也做个判断看看有没有报错

两个值都是true，应该是set成功了

**Comment by zjkyz8** [comment]
> 那可能的原因就是uid问题了。 看文档 https://github.com/deatil/go-cryptobin/blob/main/docs/sm2.md 里的uid设置确认下对不对

应该是对的，签名那边用的相同的uid，是正常的，这块招行又有啥特殊处理吗，签名那边就是有特殊处理的

**Comment by deatil** [comment]
> > 那可能的原因就是uid问题了。 看文档 https://github.com/deatil/go-cryptobin/blob/main/docs/sm2.md 里的uid设置确认下对不对
> 
> 应该是对的，签名那边用的相同的uid，是正常的，这块招行又有啥特殊处理吗，签名那边就是有特殊处理的

我这边用的处理的他们给到网上的，你这个的具体是不是一样的处理方法你需要比对下。目前不知道具体的话，就只能你那里去比对判断来给了
