### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ssqf** [deatil/go-cryptobin#12]
### 当前版本

v1.0.2021

### Golang 版本

go 1.21.0

### 是否依旧存在

可以

### bug描述

var keys = []byte{0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F}
ciphertext := crypto.FromString(data).SetKey("3aa61bf963dakktv").WithIv(keys).OnError(func(err []error).Aes().CBC().PKCS5Padding().Encrypt().ToBase64String()

没有错误，结果却为空，PKCS7Padding 正常

**Comment by deatil** [comment]
OnError 目前是没有做提前设置后会监听到后面报错的处理。所以OnError的放置位置最好是在Encrypt之后

**Comment by deatil** [comment]
最新版本优化了对称加密的 onError 获取，可以拉取新版本
