### ISSUE TITLE
[Question]: 浙里办票：电子发票SM4验签调用问题

### ISSUE THREAD

**Issue by deepdatatop** [deatil/go-cryptobin#18]
### 疑惑的地方

email: info@deepdata.cn   wechat: deepestdata

对接平台： https://dzpj.zjzwfw.gov.cn/

请问sign时，sm2的调用如何组织？目前采用以下方案，生成的signature与java版本生成的不一致，并每次都随机变动。
~~~go
	block, _ := pem.Decode([]byte(privateKeyContent))
	b, e := pkcs8.DecryptPEMBlock(block, []byte(password))
	if e == nil {
		fmt.Println("DecryptPEMBlock:", bytesToHexString(b))
		//github.com/deatil/go-cryptobin/cryptobin/sm2
		result = sm2.New().
			FromString(signPayloadBody).
			FromPKCS8PrivateKeyWithPassword([]byte(privateKeyContent), password).
			Sign().
			ToHexString()
	}
~~~

java demo:
~~~java
   private static String instCode = "xxxxxx";  //纳税人识别号
    //企业密码
    private static String password = "xxx";  // 企业密码
    //企业密钥
    private static String privateKeyContent = "-----BEGIN ENCRYPTED PRIVATE KEY-----\n" +
            "xxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/\n" +
            "vZxxxxxxxxxXfgDxxxxxxxxxxtjpNIOxxxxxxxxxxxxxxxxxxxxxx/\n" +
            "Nxxxxxxxxxxxxxxxx0K9LaPOsxAxxxxxxxxxxxxxxxxxxxxxKrAr3n\n" +
            "oSMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxFNBDt8AX\n" +
            "sexxxxxxxxxxxxxnQiLrdwVtxxxxxxxxxxxxxxxxxx/9Uzl//6RbIt\n" +
            "Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxv==\n" +
            "----END ENCRYPTED PRIVATE KEY-----";
~~~
  java签名函数：
~~~java
private static String sign(String jsonStr) {
        GovDataSDK.getInstance().init(instCode, privateKeyContent, password, EncryptTpyeEnum.SM4);
        SignedRequest request = GovDataSDK.getInstance().getRequestBuilder().generateSignedPayload(jsonStr);
        return JSON.toJSONString(request);
    }
~~~

### 对下样例中签名选择SM3摘要，请问我们如何在调用sm2加上SM3Digest()这个动作？
~~~java
//AsymmetricCipherEnum：SM2，DigestEnum：SM3

public static DsaSigner createSigner(AsymmetricCipherEnum asymmetricCipherEnum, DigestEnum digestEnum, InputStream privateKeyStream, String password) throws PKCSException, OperatorCreationException, IOException {
        X9ECParameters CURVE_PARAMS;
        switch (asymmetricCipherEnum) {
            **case SM2:
                CURVE_PARAMS = CustomNamedCurves.getByName(asymmetricCipherEnum.getCurveName());**
                switch (digestEnum) {
                    **case SM3:
                        return new Sm2Impl(CURVE_PARAMS, new SM3Digest(), privateKeyStream, password);**
//-------------
public Sm2Impl(X9ECParameters curveParameter, Digest digest, InputStream privateKeyStream, String password) throws IOException, PKCSException, OperatorCreationException {
        Security.addProvider(new BouncyCastleProvider());
        if (digest != null) {
            this.sm2Engine = new SM2Engine(digest);
        } else {
            this.sm2Engine = new SM2Engine();
        }

        this.sm2Signer = new SM2Signer();
        this.privateKeyInit = true;
        this.curve = new ECDomainParameters(curveParameter.getCurve(), curveParameter.getG(), curveParameter.getN(), curveParameter.getH());
        this.halfCurveOrder = curveParameter.getN().shiftRight(1);
        String privateKeyContent = IOUtils.toString(privateKeyStream, Charset.forName("utf-8"));
        PrivateKey privateKey = Pkcs8Utils.parseEncryptedPrivateKey(privateKeyContent, password);
        BCECPrivateKey bcecPrivateKey = (BCECPrivateKey)privateKey;
        BigInteger d = bcecPrivateKey.getD();
        ECPrivateKeyParameters privKey = new ECPrivateKeyParameters(d, this.curve);
        this.sm2Engine.init(false, privKey);
        this.sm2Signer.init(true, privKey);
    }
~~~

### 期望的结果

希望能给出cryptobin相应的签名调用方法。
例如：
~~~go
		result = sm2.New().
			FromString(signPayloadBody).
			FromPKCS8PrivateKeyWithPassword([]byte(privateKeyContent), password).
                        ********
			Sign().
			ToHexString()
~~~
[zjsw-zlbp-demo.zip](https://github.com/deatil/go-cryptobin/files/14337675/zjsw-zlbp-demo.zip)
[gov-sdk-2.0.0.20220708-jar-with-dependencies.jar.zip](https://github.com/deatil/go-cryptobin/files/14337681/gov-sdk-2.0.0.20220708-jar-with-dependencies.jar.zip)
[Uploading plate-generate-1.0.11-jar-with-dependencies.jar.zip…]()

**Comment by deatil** [comment]
SM2 签名的 java 完整代码有吗？给的附件没看到有这部分代码
生成的签名只能验证，不能直接比对

**Comment by deatil** [comment]
sm2 的签名默认就是用的 SM3，不需要管。
sign函数里的 SM4 没看到具体的代码，没法确认是怎么用的

**Comment by deepdatatop** [comment]
请发您的邮箱地址到 info@deepdata.cn 文件包太大，限制上传。

**Comment by deatil** [comment]
你直接把 generateSignedPayload 这个函数相关的代码发出来看下

**Comment by deepdatatop** [comment]
public SignedEncryptedRequest generateSignedEncryptedPayload(byte[] content, byte[] inputPassword, String inputPublicKey) {
        if (this.publicKey == null && inputPublicKey == null) {
            throw new IllegalStateException("server public key not config");
        } else {
            byte[] jsonBytes = content;

            byte[] encryptedContent;
            byte[] envelopContent;
            try {
                if (this.type != EncryptTpyeEnum.AES && this.type != EncryptTpyeEnum.RSA) {
                    if (this.type != EncryptTpyeEnum.SM4) {
                        throw new IllegalArgumentException("unknown encrypt type " + this.type.name());
                    }

                    if (inputPassword.length != 16) {
                        throw new IllegalArgumentException("passcode length should be 16");
                    }

                    encryptedContent = SymmetricFactory.createCipher(SymmetricCipherEnum.SM4).encrypt(jsonBytes, inputPassword);
                    envelopContent = this.getEncrypt(inputPublicKey).encrypt(inputPassword);
                } else {
                    byte[] kdfPassword = DigestFactory.calculateSha256(inputPassword);
                    encryptedContent = SymmetricFactory.createCipher(SymmetricCipherEnum.AES).encrypt(jsonBytes, kdfPassword);
                    envelopContent = this.getEncrypt(inputPublicKey).encrypt(kdfPassword);
                }
            } catch (Exception var15) {
                throw new RuntimeException(var15);
            }

            String payload = LiteBase64.getEncoder().encodeToString(encryptedContent);
            String envelop = LiteBase64.getEncoder().encodeToString(envelopContent);
            long timestamp = System.currentTimeMillis() / 1000L;
            String nonce = String.valueOf((int)((Math.random() * 9.0 + 1.0) * 100000.0));
            byte[] signPayloadBody = (this.instCode + payload + timestamp + nonce).getBytes();
            byte[] signature = this.getSigner().sign(signPayloadBody);
            String signatureString = HexUtils.toHexString(signature);
            return new SignedEncryptedRequest(this.instCode, payload, String.valueOf(timestamp), nonce, signatureString, envelop, this.type);
        }
    }

**Comment by deepdatatop** [comment]
private DsaSigner getSigner() {
        try {
            ByteArrayInputStream in;
            DsaSigner signer;
            if (this.type == EncryptTpyeEnum.AES) {
                in = new ByteArrayInputStream(this.privateKey);
                signer = AsymmetricFactory.createSigner(AsymmetricCipherEnum.SECP256K1, DigestEnum.SHA256, in, this.password);
                in.close();
                return signer;
            }

            if (this.type == EncryptTpyeEnum.SM4) {
                System.out.println("这里是入口！");
                in = new ByteArrayInputStream(this.privateKey);
                signer = AsymmetricFactory.createSigner(AsymmetricCipherEnum.SM2, DigestEnum.SM3, in, this.password);
                in.close();
                return signer;
            }

            if (this.type == EncryptTpyeEnum.RSA) {
                in = new ByteArrayInputStream(this.privateKey);
                signer = AsymmetricFactory.createSigner(AsymmetricCipherEnum.RSA2048, DigestEnum.SHA256, in, this.password);
                in.close();
                return signer;
            }
        } catch (Exception var3) {
            throw new RuntimeException("create signer fails", var3);
        }

        throw new IllegalStateException("unknown encrypt type");
    }

**Comment by deatil** [comment]
测试里的 SM4 是加密的生成的 json 数据，还用了 sm2 公钥加密秘钥。
getEncrypt 这个函数可以看下是用的是不是 sm2 加密，其他的组合看下逻辑用go实现下就行

**Comment by deepdatatop** [comment]
signature的生成我这边再继续探索下，目前用go直接提交java生成的签名是成功的。
**go version:** {"instCode":"91330109MA2B1MUL9G","nonce":"345047","payload":"eyJhdXRob3JpemVkTnNyc2JoIjoiOTEzMzAxMDlNQTJCMU1VTDlHIiwiZ3hmYnMiOjIsImpncnEiOiIyMDIyLTEyLTE3IiwibnNyc2JoIjoiOTEzMzAxMDlNQTJCMU1VTDlHIiwicmVxdWVzdElkIjoiRkZGRkZGRkZGRkZGRkZfMTcwODI0ODM4Mzc5NCJ9","signature":"144c1ffa438c6e95755a6cbd51ca6657641f2eb628fa6d6b809b0133ad86e7947598b303cd83299a0daf834b46229e71b6852571394127b0a114de3fd0bbe5c4","timestamp":"1708427870","type":"SM4"} <nil>
{"success":false,"needRetry":true,"errorCode":"VERIFY_ERROR","errorMsg":"VERIFY EXCEPTION","errorType":"0","idempotentBizContext":null,"data":null,"viewErrorField":null,"viewErrorMsg":"VERIFY EXCEPTION","totalRecords":0}

**java version:** {"instCode":"91330109MA2B1MUL9G","nonce":"150152","payload":"eyJhdXRob3JpemVkTnNyc2JoIjoiOTEzMzAxMDlNQTJCMU1VTDlHIiwiZ3hmYnMiOjIsImpncnEiOiIyMDIyLTEyLTE3IiwibnNyc2JoIjoiOTEzMzAxMDlNQTJCMU1VTDlHIiwicmVxdWVzdElkIjoiRkZGRkZGRkZGRkZGRkZfMTcwODI0ODM4Mzc5NCJ9","signature":"3045022100e8471c399fde6e09623665c1131ff87dcbeec504afb0efc703df57a380348a680220377a35a1425f084a1d766db379267aa5bc0712fad9c158c27e704c3c8b4d6325","timestamp":"1708410945","type":"SM4"} <nil>
{"success":true,"needRetry":false,"errorCode":"SUCCESS","errorMsg":null,"errorType":null,"idempotentBizContext":null,"data":{"totalPage":1,"totalCount":4},"viewErrorField":null,"viewErrorMsg":"成功","totalRecords":0}

**Comment by deatil** [comment]
java是能跑的吗？用个测试的公钥私钥测试一组数据发下，看看能不能验证

**Comment by deepdatatop** [comment]
验签成功！感谢支持。

浙江省区块链电子发票（票据）综合服务平台  浙里办票（ZLBP ）
go version: {"instCode":"91330109MA2B1MUL9G","nonce":"214222","payload":"eyJhdXRob3JpemVkTnNyc2JoIjoiOTEzMzAxMDlNQTJCMU1VTDlHIiwiZ3hmYnMiOjIsImpncnEiOiIyMDIyLTEyLTE3IiwibnNyc2JoIjoiOTEzMzAxMDlNQTJCMU1VTDlHIiwicmVxdWVzdElkIjoiRkZGRkZGRkZGRkZGRkZfMTcwODQzMDIwNTIzNyJ9","signature":"304502203fb8*55a8a27d258750ac239680ec3326de910112350ec701c47e73c033ebc09022100dd7e439eacd67e1acc798a622076a*fc78a7ed914f02edca9574a9320086f05a","timestamp":"1708430205","type":"SM4"} <nil>
{"success":true,"needRetry":false,"errorCode":"SUCCESS","errorMsg":null,"errorType":null,"idempotentBizContext":null,"data":{"totalPage":1,"totalCount":4},"viewErrorField":null,"viewErrorMsg":"成功","totalRecords":0}

**Comment by deatil** [comment]
ok
