### ISSUE TITLE
[Question]: 请教sm2如何与snowland-smx-python中sm2的加解密互通

### ISSUE THREAD

**Issue by yujingyue9166** [deatil/go-cryptobin#24]
### 疑惑的地方

您好，我使用 python snowland-smx-python 中无法解密[go-cryptobin] sm2密文，同样 go-cryptobin 中sm2 也无法解密snowland-smx-python生成的密文
```python
import base64
from pysmx.SM2 import Encrypt,Decrypt
sk = base64.b64decode("qeMGjqEmmy2uQjZy87yrzbLXW/w1OLDvmjO3MlS2f3o=")
pk = base64.b64decode("hbNGUgD4vRE9fYYoyDQIB7QM47at6IEL+Pd9H6yeW12l7rMi6WrzspN5xmakfdZ4sWsTqUix0w+rgAIK2CsD3g==")
msg = "hello world"
len_para = 64
cipher_text = Encrypt(msg,pk,len_para, 0)
print("cipher_text",cipher_text)
decrypt_text = Decrypt(cipher_text,sk,len_para)
print("decrypt_text",decrypt_text)

newcipher_text ="BBtL0SS42RNWWRe1G9cHcAaKsHaflA44DTXQpSsuDap/BZiZoQ8Cc+qJRI70/utTWZlKg8HzK8HywtvRWlXK2icptvV5ABum+nqA17g9V7XRnaoepXO2BrW9Jr1q4xkpQumov9CLpLbSRA=="
decrypt_text = Decrypt(base64.b64decode(newcipher_text),sk,len_para)
print("decrypt_text",decrypt_text)

``` 

### 期望的结果

想请教下，应该如何互通加解密。谢谢

**Comment by yujingyue9166** [comment]
> 你go的使用代码有吗？发个使用的代码

谢谢大佬回复，
```go
package main

import (
	"encoding/base64"
	"fmt"
	"github.com/deatil/go-cryptobin/cryptobin/sm2"
	"io/ioutil"
)
func main() {
        sm2key := "qeMGjqEmmy2uQjZy87yrzbLXW/w1OLDvmjO3MlS2f3o="
	sm2keyBytes, _ := base64.StdEncoding.DecodeString(sm2key)
       data := "test-pass"

	sm2pk := sm2.NewSM2().
		FromPrivateKeyBytes(sm2keyBytes).
		MakePublicKey()

	fmt.Println("公钥from sm2pk", sm2pk)

	en := sm2.
		FromString(data).
		FromPrivateKeyBytes(sm2keyBytes).
		MakePublicKey().
		SetMode("C1C3C2"). // C1C3C2 | C1C2C3
		//EncryptASN1()
		Encrypt()

	fmt.Println("加密结果", en)
	enData := en.ToBase64String()
	fmt.Println("加密结果", enData)
	de := sm2.
		FromBase64String(enData).
		FromPrivateKeyBytes(sm2keyBytes).
		SetMode("C1C3C2"). // C1C3C2 | C1C2C3
		//DecryptASN1()
		Decrypt()
	deData := de.ToString()

	fmt.Println("解密结果", deData)
	endata := "1LNM8vTVc7MrXRZMb+htuEhyXRYiQMavcYky1x7an3jPa4JUa9Vgp/UcKahda5Lpbhy4RshUZXk8HWkrUoNyDOrme/cQES6IF4I1AzZT0kjzhzL/sZnCqK76dFAd4qa1hSuZLjUTLpnjYs0="
	//fmt.Println("数据长度", len(endata))

	dedata := sm2.FromHexString(endata).FromPrivateKeyBytes(sm2keyBytes).
		SetMode("C1C3C2"). // C1C3C2 | C1C2C3
		DecryptASN1()
	//Decrypt()
	fmt.Println("解密结果", dedata.ToString())

}

```

**Comment by deatil** [comment]
第二个的解密改成
~~~go
dedata := sm2.FromBase64String(endata).
FromPrivateKeyBytes(sm2keyBytes).
		SetMode("C1C3C2"). // C1C3C2 | C1C2C3
		Decrypt()
~~~
解py用这个解该说可以解

**Comment by yujingyue9166** [comment]
按照Decrypt() 解密结果 {0xc00001e390 <nil> 0 [] [212 179 76 242 244 213 115 179 43 93 22 76 11
1 232 109 184 72 114 93 22 34 64 198 175 113 137 50 215 30 218 159 120 207 107 1
30 84 107 213 96 167 245 28 41 168 93 107 146 233 110 28 184 70 200 84 101 121 6
0 29 105 43 82 131 114 12 234 230 123 247 16 17 46 136 23 130 53 3 54 83 210 72 
243 135 50 255 177 153 194 168 174 250 116 80 29 226 166 181 133 43 153 46 53 19
 46 153 227 98 205] [] <nil> [49 50 51 52 53 54 55 56 49 50 51 52 53 54 55 56] f
alse [cryptobin/sm2: encrypt data is error.]}
按照DecryptASN1() 解密结果 {0xc00001e390 <nil> 0 [] [212 179 76 242 244 213 115 179 43 93 22 76 11
1 232 109 184 72 114 93 22 34 64 198 175 113 137 50 215 30 218 159 120 207 107 1
30 84 107 213 96 167 245 28 41 168 93 107 146 233 110 28 184 70 200 84 101 121 6
0 29 105 43 82 131 114 12 234 230 123 247 16 17 46 136 23 130 53 3 54 83 210 72 
243 135 50 255 177 153 194 168 174 250 116 80 29 226 166 181 133 43 153 46 53 19
 46 153 227 98 205] [] <nil> [49 50 51 52 53 54 55 56 49 50 51 52 53 54 55 56] f
alse [asn1: structure error: length too large]}

**Comment by deatil** [comment]
你第二个的endata是py加密的数据？

**Comment by yujingyue9166** [comment]
是的

**Comment by deatil** [comment]
发现问题了，解密py的加密，需要前置加4可以看这个 https://github.com/deatil/go-cryptobin/blob/main/cryptobin/sm2/sm2_test.go#L729 ，go加密后需要去掉前置的4给py解密
