### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WyntersN** [deatil/go-cryptobin#26]
### 当前版本

v1.0.2071

### Golang 版本

1.22.0

### 是否依旧存在

可以

### bug描述

示例中

crypto.
		FromString("useData").
		SetKey("dfertf12dfertf12").
		Encrypt().
		ToBase64String()
		
		
		输出出来是空的
		
		
		
		
		
![image](https://github.com/deatil/go-cryptobin/assets/27792650/2a1dcfa6-8b87-4653-95d1-4e9a3d8eb6db)

**Comment by deatil** [comment]
%x换成%s试下

**Comment by deatil** [comment]
可以先看下有没有报错
~~~go
var err = crypto.
FromString("useData").
SetKey("dfertf12dfertf12").
Encrypt().
Error() 
~~~

**Comment by deatil** [comment]
发现问题了，文档给的测试代码有点问题，已经更新了。
可以看下最新的文档
