### ISSUE TITLE
[Feature]: 关于CCM加解密iv长度

### ISSUE THREAD

**Issue by ceil124** [deatil/go-cryptobin#28]
### 功能描述以及必要性描述

目前情况：
目前框架里encrypt_mode.go的的加解密实现：
1、指定tag_size时，向量长度默认取框架默认值12
2、不指定tag_size时，tag_size取默认值16，而向量取iv实际长度

框架里的代码实现：
  tagSize := opt.Config().GetInt("tag_size")
  if tagSize > 0 {
      aead, err = ccm.NewCCMWithTagSize(block, tagSize)
  } else {
      aead, err = ccm.NewCCMWithNonceSize(block, len(iv))
  }

而CCM加密中加密向量iv的长度只限制了起始长度7~13字节，在指定tagSize的情况，iv长度不一定为框架里的默认值12

### 建议和方案

希望支持指定tagSize的同时，iv取动态长度。或者支持能同时指定tagSize和nonceSize值。

**Comment by deatil** [comment]
更新了新版，ccm和gcm的设置不跟iv绑定了

**Comment by ceil124** [comment]
感谢，可以正常运行
