### ISSUE TITLE
AES/ECB/PKCS5Padding加密失败

### ISSUE THREAD

**Issue by FourLeafTec** [deatil/go-cryptobin#4]
代码:

```
crypto.FromBytes(src).
		SetKey("{key}").
		Aes().
		ECB().
		PKCS5Padding().
		Encrypt()
```

日志：

```
[Cryptobin: [CipherEncrypt()] the length of the completed data must be an integer multiple of the block, the completed data size is 168, block size is 16]
```

**Comment by deatil** [comment]
有具体用的哪个版本吗？测试是没有复现这个问题

**Comment by deatil** [comment]
还有一个 就是 ecb 模式对需要加密的数据长度会有一些要求，比如 8 到 17之间的或者类似数据长度。不需要有要求的话用 `PKCS7Padding` 最好。网上大多这个 `pkcs5` 是指的 `pkcs7`

**Comment by deatil** [comment]
@UovTech @FourLeafTec `pkcs5` 在报里强制使用的是 8 长度，补码的时候不满足情况的时候是有问题的。所以这个得看加密的数据长度。最好的就是 `pkcs7` 没有数据长度限制

**Comment by deatil** [comment]
~~~
PKCS5Padding限定填充大小是8Byte(64bit)，AES最小块大小是16Byte(128bit)，所以AES用不了PKCS5Padding。
~~~
网上的一个说法是这样的，aes不能用 pkcs5

**Comment by FourLeafTec** [comment]
软件版本是：v1.0.1047
对方是Java，组合AES/ECB/PKCS5，实际处理结果与PKCS7相同，估计就是Java那边实现的问题

@UovTech 你获取一下cypt.Errors,就看到了

我这边没问题了，@UovTech 你那确认一下没问题就关闭吧

**Comment by UovTech** [comment]
关闭吧，换pkcs7已解决 @FourLeafTec @deatil
