### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by pigfu** [deatil/go-cryptobin#5]
### 疑惑的地方

你好，我在进行招行对接时，加密结果与招行给的demo执行结果不一样，有什么建议吗？

### 期望的结果

可能的原因

**Comment by pigfu** [comment]
`const (
	userId = "1234567812345678"
)

func Sm2Sign(content, privateKey string) string {
	sm2keyBytes, _ := hex.DecodeString(privateKey)
	return cryptobinsm2.NewSM2().
		FromPrivateKeyBytes(sm2keyBytes).
		FromString(content).
		SignHex([]byte(userId)).
		ToBase64String()
}
func TestSm2Sign(t *testing.T) {
	content := "biz_content={\"orderId\":\"389427178935\",\"notifyUrl\":\"https://testmarketing.kdzl.cn/store/pay/callback/cmb\",\"merId\":\"3089991701201JS\",\"body\":\"test something\",\"userId\":\"N003638229\",\"currencyCode\":\"156\",\"txnAmt\":\"378000\"}&encoding=UTF-8&signMethod=02&version=0.0.1"
	fmt.Println(content)
	privateKey := "D5F2AFA24E6BA9071B54A8C9AD735F9A1DE9C4657FA386C09B592694BC118B38"
	fmt.Println(Sm2Sign(content, privateKey))
}
`

**Comment by deatil** [comment]
content 数据不是json吗

**Comment by deatil** [comment]
使用方法是没有问题的。看你给的key是hex的，那demo生成的数据是hex的还是base64的？

**Comment by pigfu** [comment]
看demo里的私钥是 hex的

**Comment by deatil** [comment]
发一个demo生成的值

**Comment by deatil** [comment]
signRawToAsn1 这个可以发一下，demo生成的值好像不是hex的，问题估计在这

**Comment by deatil** [comment]
sign换成这个SignAsn1试下

**Comment by pigfu** [comment]
我试试，tks

**Comment by pigfu** [comment]
` public static byte[] signSm3WithSm2Asn1Rs(byte[] msg, byte[] userId, PrivateKey privateKey){
        try {
            SM2ParameterSpec parameterSpec = new SM2ParameterSpec(userId);
            Signature signer = Signature.getInstance("SM3withSM2", "BC");
            signer.setParameter(parameterSpec);
            signer.initSign(privateKey, new SecureRandom());
            signer.update(msg, 0, msg.length);
            byte[] sig = signer.sign();
            return sig;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }`

你好，还是不太行，会不会是demo里的参数"SM3withSM2"  "BC" 比较特殊？？

**Comment by pigfu** [comment]
`public static byte[] signSm3WithSm2Asn1Rs(byte[] msg, byte[] userId, PrivateKey privateKey){
        try {
            SM2ParameterSpec parameterSpec = new SM2ParameterSpec(userId);
            Signature signer = Signature.getInstance("SM3withSM2", "BC");
            signer.setParameter(parameterSpec);
            signer.initSign(privateKey, new SecureRandom());
            signer.update(msg, 0, msg.length);
            byte[] sig = signer.sign();
            return sig;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }`

你好还是不太行，会不会是demo里的参数 "SM3withSM2", "BC"参数原因？

**Comment by pigfu** [comment]
我对sm2一窍不通

**Comment by deatil** [comment]
signRawToAsn1 这个函数发一下

**Comment by deatil** [comment]
BC是提供方，正常的话该说不会有影响

**Comment by deatil** [comment]
先确认下demo生成的签名多少位。现在是验证不通过吗？还是你怎么比对的？

**Comment by pigfu** [comment]
签名结果不一样

**Comment by pigfu** [comment]
`private static byte[] signRawToAsn1(byte[] bcCipTxt) throws Exception {

        byte[] netSignCipTxt = new byte[73];

        byte[] signR = new byte[32];
        byte[] signS = new byte[32];

        System.arraycopy(bcCipTxt, 0, signR, 0, 32);
        System.arraycopy(bcCipTxt, 32, signS, 0, 32);

        //signR补位
        int wPos = 4;
        netSignCipTxt[0] = 0x30;
        netSignCipTxt[2] = 0x02;
        if( (signR[0] & 0xFF) >= 128 )
        {
            netSignCipTxt[wPos - 1] = 0x21;
            netSignCipTxt[wPos] = 0x00;
            wPos += 1;
        }
        else
        {
            netSignCipTxt[wPos - 1] = 0x20;
        }
        System.arraycopy(signR, 0, netSignCipTxt, wPos, 32);
        wPos += 32;

        //signS补位
        netSignCipTxt[wPos] = 0x02;
        wPos += 1;
        if( (signS[0] & 0xFF) >= 128 )
        {
            netSignCipTxt[wPos] = 0x21;
            wPos += 1;
            netSignCipTxt[wPos] = 0x00;
            wPos += 1;
        }
        else
        {
            netSignCipTxt[wPos] = 0x20;
            wPos += 1;
        }
        System.arraycopy(signS, 0, netSignCipTxt, wPos, 32);
        wPos += 32;

        if(70 == wPos)
        {
            netSignCipTxt[1] = 0x44;
        }
        else if(71 == wPos)
        {
            netSignCipTxt[1] = 0x45;
        }
        else if(72== wPos)
        {
            netSignCipTxt[1] = 0x46;
        }
        else
        {
            throw new Exception("signRawToAsn1 Error!");
        }

        byte[] resultBytes = new byte[wPos];
        System.arraycopy(netSignCipTxt, 0, resultBytes, 0, wPos);

        return resultBytes;
    }
`

**Comment by pigfu** [comment]
难道是招行有特殊处理的逻辑？？

**Comment by pigfu** [comment]
go:
=== RUN   TestSm2Sign
签名内容 biz_content={"orderId":"389427178935","notifyUrl":"h    ttps://testmarketing.kdzl.cn/store/pay/callback/cmb","merId":"3089991701201JS","body":"test something","userId":"N003638229","currencyCode":"156","txnAmt":"378000"}&encoding=UTF-8&signMethod=02&version=0.0.1
签名内容 MEYCIQCvTnuI+GXi2YtGfrltbVwOfvK3Vbxjalgv9i+zNaoLVAIhAN/f/Pr    GbwCmAxkm5jtbNpL9CiH12s93/rp8sLmKXbnp
--- PASS: TestSm2Sign (0.00s)

**Comment by pigfu** [comment]
java demo:
签名内容：biz_content={"orderId":"389427178935","notifyUrl":"https://testmarketing.kdzl.cn/store/pay/callback/cmb","merId":"3089991701201JS","body":"test something","userId":"N003638229","currencyCode":"156","txnAmt":"378000"}&encoding=UTF-8&signMethod=02&version=0.0.1
签名结果：MEYCIQCNCOm87k4pGA4Qx1TwD3qHZDYQN5uSlVutfZqfYEIDIgIhANLqqvxe4HfCpjD/O5dbjHynXMHsFxFrF+w9kEc2VjB3

**Comment by deatil** [comment]
> 签名结果不一样

sm2的签名，需要去验证，不能看是不是相等。sm2不是md5这种

**Comment by deatil** [comment]
go生成的签名用java去验证

**Comment by pigfu** [comment]
> > 签名结果不一样
> 
> sm2的签名，需要去验证，不能看是不是相等。sm2不是md5这种

刚接触sm2,没注意到这点，非常谢谢，目前go签名后的结果java demo那边验签通过了，后续试试调用招行api

**Comment by deatil** [comment]
ok

**Comment by tanjl855** [comment]
> ok

大佬，有空可以看一下上面嘛

**Comment by pigfu** [comment]
你也对接招行？

**Comment by pigfu** [comment]
> > ok
> 
> 大佬，有空可以看一下上面嘛

你也对接招行？搞定没？

**Comment by pigfu** [comment]
> > ok
> 
> 大佬，有空可以看一下上面嘛

注意下，招行给的公钥不是最终的公钥，需要用招行给的国密局统一下发的不变的USER_ID和固定的公钥头兑换下
```go
func parseBase64TRawKey(publicKey string) string {
	sm2keyBytes, _ := base64.StdEncoding.DecodeString(publicKey)
	hexKey := hex.EncodeToString(sm2keyBytes)
	if !strings.HasPrefix(hexKey, publicKeyPrefix) {
		return ""
	}
	return strings.TrimPrefix(hexKey, publicKeyPrefix)
}
```

**Comment by deatil** [comment]
> > > > 签名结果不一样
> > > 
> > > 
> > > sm2的签名，需要去验证，不能看是不是相等。sm2不是md5这种
> > 
> > 
> > 刚接触sm2,没注意到这点，非常谢谢，目前go签名后的结果java demo那边验签通过了，后续试试调用招行api
> 
> 请问是怎么解决的？
> 
> ```
> type SZsyh struct {
> 	PrivateKey string
> }
> 
> func (s2 *SZsyh) CMBSM2SignWithSM3(forSignStr string, uid []byte) (string, error) {
> 
> 	privateKey := s2.GetSm2PrivateKey()
> 
> 	r, s, err := sm2.Sm2Sign(privateKey, []byte(forSignStr), uid, rand.Reader)
> 	if err != nil {
> 		return "", err
> 	}
> 
> 	rBytes, sBytes := r.Bytes(), s.Bytes()
> 	rLen, sLen := len(rBytes), len(sBytes)
> 	regularSize := 32
> 
> 	if rLen < regularSize {
> 		for i := 0; i < regularSize-rLen; i++ {
> 			rBytes = append(rBytes, 0)
> 		}
> 	}
> 	if sLen < regularSize {
> 		for i := 0; i < regularSize-sLen; i++ {
> 			sBytes = append(sBytes, 0)
> 		}
> 	}
> 
> 	var buffer bytes.Buffer
> 	buffer.Write(rBytes)
> 	buffer.Write(sBytes)
> 	return base64.StdEncoding.EncodeToString(buffer.Bytes()), nil
> }
> 
> func SM3Sum(forSignStr string) string {
> 	h := sm3.New()
> 	h.Write([]byte(forSignStr))
> 	return strings.ToUpper(hex.EncodeToString(h.Sum(nil)))
> }
> 
> func (s *SZsyh) GetSm2PrivateKey() *sm2.PrivateKey {
> 	privateKeyBytes, _ := base64.StdEncoding.DecodeString(s.PrivateKey)
> 	HexPrivateKey := hex.EncodeToString(privateKeyBytes)
> 	d := new(big.Int)
> 	d.SetString(HexPrivateKey, 16)
> 	privateKey := new(sm2.PrivateKey)
> 	privateKey.D = d
> 	curve := sm2.P256Sm2()
> 	privateKey.PublicKey.Curve = curve
> 	privateKey.PublicKey.X, privateKey.PublicKey.Y = curve.ScalarBaseMult(d.Bytes())
> 
> 	return privateKey
> }
> ```
> 
> 我的方法验不过。。

r,s 的补0是前置不是后置

**Comment by tanjl855** [comment]
> > > ok
> > 
> > 
> > 大佬，有空可以看一下上面嘛
> 
> 你也对接招行？搞定没？

早些时候已经搞定了，确实是自己写的有问题，害
