### ISSUE TITLE
[Question]: 请教招商银行生成签名后使用报错

### ISSUE THREAD

**Issue by guihai** [deatil/go-cryptobin#6]
### 疑惑的地方

~~~go
func (s *SM4) Sm2Sign(uid, skey, data string) string {

	sm2keyBytes, _ := base64.StdEncoding.DecodeString(skey)

	return cryptobin_sm2.NewSM2().
		FromPrivateKeyBytes(sm2keyBytes).
		FromString(data).
		SignHex([]byte(uid)).
		ToBase64String()

}
~~~

以上代码，生成签名使用，招商报错 签名校验失败[Failed to
 verify data using SM2 public key. case by : It’s just a failure to check, not an exception.]

### 期望的结果

请教

**Comment by deatil** [comment]
感觉招商那边的版本不一样。

**Comment by guihai** [comment]
您好，以下是测试数据
用户id 已经补位了
ID16 := "N002462434000000"
私钥
key := "NBtl7WnuUtA2v5FaebEkU0/Jj1IodLGT6lQqwkzmd2E="
这是招行工具生成的签名 目标数据
mu := "tOJyCP3sVfARxqx42d8tSKwpf/OCueEaaFojcR/msfarSwkfXQoHmtbjqdf/xixqc7ay+rrRuALXnjRVJo/uwQ=="

`
cryptobin_sm2.NewSM2().
		FromPrivateKeyBytes(sm2keyBytes).
		FromString(data).
		SignHex([]byte(uid)).
		ToBase64String()
`
这个方法生成的签名是服务目标长度的，但是不能通过招行验签

**Comment by deatil** [comment]
能提供下demo生成签名的部分吗？招商银行的版本看起来是有好几个，需要根据 demo 来确认才行

**Comment by deatil** [comment]
用来签名的 data 有吗？用个测试数据用测试工具生成一个发下看看

**Comment by deatil** [comment]
还没解决可以再重新开个issue
